# -*- coding: utf-8 -*-
"""timeAnalysis.ipynb

Automatically generated by Colaboratory.
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import csv
import os

print(os.listdir("./")) # make sure train.csv is in current directory

def readCSV(filename):
    """
    takes in a filename
    returns a numpy array, with the first row as the
        timestamp in seconds, and the second row
        as the fps across the last time block
    """
    results = []
    with open(filename) as csv_file:
        reader = csv.reader(csv_file, delimiter=',')
        for line in reader:
            step = float(line[0])
            timestamp = float(line[1])
            fps = float(line[2])
            results.append([timestamp, fps])

    return np.array(results).T

directory='./'
kd = []
naive = []
cpu = []
for filename in os.listdir(directory):
    if filename.endswith(".csv"): 
        data = readCSV(filename)
        t = data[0,:-1]
        t1 = data[0,1:]
        dt = t1-t
        avg = np.average(dt)
        if 'KDtree' in filename:
            print(int(filename[-8:-4]),' KDtree average iteration time: ', avg)
            kd.append( ( int(filename[-8:-4]),avg ) )
        elif 'KDtree' not in filename and 'gpu' in filename:
            l = 11-len(filename)
            print(int(filename[-8:-4]),' naive average iteration time: ', avg)
            naive.append( ( int(filename[-8:-4]),avg ) )
        else:
            print('cpu average iteration time: ', avg)
            cpu.append(avg)

kd = np.array(kd).T
naive = np.array(naive).T
cpu = np.array(cpu)